### ISSUE TITLE
What is minimum supported Android version?

### ISSUE THREAD

**Issue by LukaszGrela** [yahoo/squidb#10]
I would like to use it from 2.3.3 (API10) is it possible? When I've setup Android Studio to use it (project has minimum API10) I've got following error:

    C:\Users\[EDIT]\app\src\main\AndroidManifest.xml:0:0 Error:
        uses-sdk:minSdkVersion 10 cannot be smaller than version 14 declared in library C:\Users\[EDIT]\app\build\intermediates\exploded-aar\com.yahoo.squidb\squidb\1.0\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.yahoo.squidb" to force usage

        FAILED

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':app:processDebugManifest'.
        > Manifest merger failed : uses-sdk:minSdkVersion 10 cannot be smaller than version 14 declared in library C:\Users\[EDIT]\app\build\intermediates\exploded-aar\com.yahoo.squidb\squidb\1.0\AndroidManifest.xml
        Suggestion: use tools:overrideLibrary="com.yahoo.squidb" to force usage

Does it mean that API level 14 is lowest it can handle?

**Comment by LukaszGrela** [comment]
I guess this is the answer:)
https://github.com/yahoo/squidb/wiki/Support-for-Pre-ICS

**Comment by sbosley** [comment]
Yep! One other thing to be aware of--write-ahead logging and beginTransactionNonExclusive() will not be available pre-ICS, as they were added in api 11. I'll update the wiki to note that.
