### ISSUE TITLE
SquidCursorLoader with android.support.v4

### ISSUE THREAD

**Issue by inawlaljar** [yahoo/squidb#105]
Hi, 
I have a fragment that extends android.support.v4.app.Fragment and implements android.support.v4.app.LoaderManager.LoaderCallbacks<SquidCursor<Organization>>

It's either conflicts with getLoaderManager().initLoader(0, null, this); Or android.support.v4.content.Loader<SquidCursor<Organization>> onCreateLoader(int id, Bundle args)  on return. 

It seems to me that SquidCursorLoader doesn't allow casting to android.app.loader.

**Comment by sbosley** [comment]
You want SquidSupportCursorLoader --  see [this wiki page](https://github.com/yahoo/squidb/wiki/Using-SquidCursorLoader#when-using-the-support-library).
