### ISSUE TITLE
(Wiki-request) Explanation and example usage of (custom) SQLite functions using the abstract Functions class

### ISSUE THREAD

**Issue by dotWee** [yahoo/squidb#108]

**Comment by sbosley** [comment]
Can you give some more details about your function? If it's a function that takes some arguments, you can simply use `Function.functionWithArguments("functionName", arg1, arg2, ...)`. Or did you have something else in mind?

**Comment by dotWee** [comment]
I'm actually not sure how to use SQLite functions with Squidb. For example, if I want to use the date function: `SELECT WHERE (property) IS date('now')` ([¹](https://www.sqlite.org/lang_datefunc.html)), which methods should I use and how to implement it into a query?

**Comment by sbosley** [comment]
Have you seen [this wiki page](https://github.com/yahoo/squidb/wiki/Fields,-Properties,-and-Functions#functions)? It outlines most of the basic use cases for functions.

SquiDB doesn't build in a wrapper for every SQLite function, but for the ones it doesn't you can use Function.functionWithArguments as I suggested above. Criterions generally work with arbitrary objects, including Functions. So in addition to doing `Model.MY_PROPERTY.eq(1)` you can do `Model.MY_PROPERTY.eq(someFunction)`, e.g.:

```java
Function dateFunction = Function.functionWithArguments("date", "now", otherArgs);
Query query = Query.select()
    .from(Model.TABLE)
    .where(Model.MY_PROPERTY.is(dateFunction));
```

Does that help?

**Comment by dotWee** [comment]
That helped me a lot! Thanks!
