### ISSUE TITLE
Hello SquiDB sample project

### ISSUE THREAD

**Issue by LukaszGrela** [yahoo/squidb#11]
Can you prepare a simple "hello world" sampel project that will show base SquiDB features?

e.g. https://github.com/yahoo/squidb/wiki/Setting-up-a-database-for-your-app should contain an example of the database and the usage - I've found it on the readme.md but still this would be useful as it is hard to collect all necessary elements to make working app.

**Comment by LukaszGrela** [comment]
On the side note, how can I call some SQLite functions from within the query?

    -- select all books details with author list and category names list
    SELECT b.title,b.isbn,b.isbn13,b.year,b.pages,b.edition,
        GROUP_CONCAT(
            DISTINCT CASE
            WHEN ad.second_name IS NULL
                THEN ad.name||" "||ad.surname
                ELSE ad.name||" "||ad.second_name||" "||ad.surname
        END) AS author,
        GROUP_CONCAT(
            DISTINCT
            c.name) AS category
    FROM books AS b
    JOIN bookAuthor AS a ON a.fk_book = b._id
    JOIN authors AS ad ON ad._id = a.fk_author
    JOIN bookCategory AS bc ON bc.fk_book = b._id
    JOIN categories AS c ON c._id = bc.fk_category
    GROUP BY b._id

Like in above example the GROUP_CONCAT, DISTINCT etc.

**Comment by sbosley** [comment]
I believe a sample project is in the works (cc @jdkoren -- would your ContentProvider example work well for this?)

Your example is pretty easy to build with one minor caveat--you've made me realize our built-in support for DISTINCT in functions is somewhat lacking. That's a totally valid feature request that I should be able to address pretty soon. But in general, here's how you'd compose functions:

```java
Function<String> firstLastName = Function.strConcat(Author.NAME, " ", Author.SURNAME);
Function<String> allNames = Function.strConcat(Author.NAME, " ", Author.SECOND_NAME, " ", Author.SURNAME);
Function<String> whichName = Function.caseWhen(Author.SECOND_NAME.isNull(), firstLastName, secondName).end();
Function<String> concatNames = Function.groupConcat(whichName); // This is where our DISTINCT support is lacking--I'll add things like Function.<someaggregatefunction>Distinct to the API

StringProperty author = StringProperty.fromFunction(concatNames, "author"); // this becomes <big group concat function> as author
```

Hope that makes sense! Let me know if you have any more questions, and I'll post back to this issue when our DISTINCT support is better.

**Comment by sbosley** [comment]
@LukaszGrela I've merged a PR that adds DISTINCT versions of the aggregate functions to our built-in function objects, so the exact version of your query is now pretty easily doable. Once you've translated your table schemas to model specs, the query you described would look like this:

```java
Function<String> authorCase = Function.caseWhen(Author.SECOND_NAME.isNull(),
    Function.strConcat(Author.NAME, " ", Author.SURNAME),
    Function.strConcat(Author.NAME, " ", Author.SECOND_NAME, " ", Author.SURNAME));
StringProperty author = StringProperty.fromFunction(Function.groupConcatDistinct(authorCase), "author");
StringProperty category = StringProperty.fromFunction(Function.groupConcatDistinct(Category.NAME), "category");

Query query = Query.select(Book.TITLE, Book.ISBN, Book.ISBN_13, Book.YEAR, 
    Book.PAGES, Book.EDITION, author, category)
    .from(Book.TABLE)
    .innerJoin(BookAuthor.TABLE, BookAuthor.FK_BOOK.eq(Book.ID))
    .innerJoin(Author.TABLE, Author.ID.eq(BookAuthor.FK_AUTHOR))
    .innerJoin(BookCategory.TABLE, BookCategory.FK_BOOK.eq(Book.ID))
    .innerJoin(Category.TABLE, Category.ID.eq(BookCategory.FK_CATEGORY))
    .groupBy(Book.ID);
```
Hope that helps! I'll leave this issue open while we finish up a sample project.

**Comment by LukaszGrela** [comment]
What would be the result of this query? Do I need to create a new class that will contain all book details as defined by SELECT statement?

**Comment by sbosley** [comment]
Not necessarily. You can read the cursor results using any model object or directly from the cursor. This wiki page describes both ways: [Using SquidCursor](https://github.com/yahoo/squidb/wiki/Using-SquidCursor).

If you prefer though, or if this query is particularly common, you could make a [ViewModel](https://github.com/yahoo/squidb/wiki/Model-specs-for-SQL-views)

**Comment by jdkoren** [comment]
@LukaszGrela It's the same query you originally posted, so the cursor will have all the columns that that query produces. Notice that @sbosley created `StringProperty`s for the functions; you would use those to read the values out of the Cursor (or a model created from it), e.g.:

```java
// continued from above code snippet
SquidCursor<Book> cursor = databaseDao.query(Book.class, query);
cursor.moveToFirst();
String authorName = cursor.get(author);
// or this
Book book = new Book(cursor);
String authorName = book.get(author); // not a property of Book, but was read into model from cursor
```

Your idea of creating another model to represent this particular query is actually perfectly valid. To do that, you would make a ViewModel using the `@ViewModelSpec`. Those specs refer to properties of other models (like Book), but can include other statically defined ones (like the author and category functions from above). In that case you could use that model instead and it would have generated methods for `getAuthor()`, `getCategory()`, and anything else you add to the spec.

If this is a query you plan to do often, you might consider having this as a view in your SQLite database, which is exactly what ViewModelSpec is for. If not, you can still create a ViewModelSpec, but specify `isSubquery = true` in the annotation.

See [Model Specs for SQL Views](https://github.com/yahoo/squidb/wiki/Model-specs-for-SQL-views)

**Comment by jdkoren** [comment]
@LukaszGrela I've added a sample of how a `ViewModelSpec` might look for this query. [Sample ViewModelSpec](https://gist.github.com/jdkoren/f6dd069fb45598da4501)

**Comment by qiao236349845** [comment]
@LukaszGrela   I am a Chinese，my words express may not clearly,the  squidb test demo can not running nomarl, it seems lack of something，I want a hello squidb demo,can you mail send to me? thank you.my email address: qiao236349845@163.com
