### ISSUE TITLE
[WIKI] How to set up SquiDB in Android Studio - sample code without closing apostrophe

### ISSUE THREAD

**Issue by LukaszGrela** [yahoo/squidb#13]
First bit of code doesnt have closing apostrophe in following lines:

    project(':squidb').projectDir = new File(settingsDir, '../path_to_cloned_root/squidb)
    [cut]
    project(':squidb-annotations').projectDir = new File(settingsDir, '../path_to_cloned_root/squidb-annotations)
    [cut]
    project(':squidb-processor').projectDir = new File(settingsDir, '../path_to_cloned_root/squidb-processor)

**Comment by sbosley** [comment]
Fixed, thanks!
