### ISSUE TITLE
UriNotifier#addUrisToNotify sample code in JS Docs

### ISSUE THREAD

**Issue by LukaszGrela** [yahoo/squidb#15]
I was looking on how to force my cursor to update when I add new entry (modify data) and found something called `UriNotifier#addUrisToNotify` (btw. such things could be added to WIKI:) ) but the sample code in JS Doc has a missing bracket here

          if (Student.TABLE.equals(table) {

and it should be

          if (Student.TABLE.equals(table)) {

on the side note, the example contained

`uris.add(Student.CONTENT_URI);`

Is the CONTENT_URI automatically generated? If so what my Table spec needs to have as my generated class doesnt have it.

**Comment by sbosley** [comment]
No, the content uri is not automatically generated. If you declare any public static final fields in your spec files though, they will be copied to the generated model class.

Thanks for the note about the javadocs, we'll fix it. And yes, the UriNotifier is a relatively new feature so we haven't written a wiki page for it yet. We'll get to it :) Thanks!

**Comment by LukaszGrela** [comment]
:) thanks for your help:)

**Comment by sbosley** [comment]
Had a little extra time this afternoon so I added a wiki page for the [UriNotifiers](https://github.com/yahoo/squidb/wiki/Listening-for-data-changes-with-UriNotifier). Thanks again for the feedback, feel free to keep it coming!

**Comment by LukaszGrela** [comment]
Thanks for the WIKI page:)
