### ISSUE TITLE
Question: is is possible to import&export entities classes into strings?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [yahoo/squidb#158]
Suppose I have a class that has the annotation "@TableModelSpec" for it, which created an entity class.
Is it possible to import&export the created class into a string (for example using a Json format) ?

**Comment by jdkoren** [comment]
I don't quite understand your question. Generally speaking, the generated class is exactly that: a Java class. You can do with it whatever you could do with any Java class. If your goal is in some way to serialize it, be aware that you must account for changes to the model spec (just as with serialization you must be wary of changes to the serialized class that make it impossible for Java to deserialize it from the persisted data).

**Comment by sbosley** [comment]
You could write a [`@ModelMethod`](https://github.com/yahoo/squidb/wiki/Advanced-model-spec-options#modelmethod) to manually implement serialization, or if you're feeling very adventurous write a [code generation plugin](https://github.com/yahoo/squidb/wiki/Taking-control-of-code-generation#writing-code-generation-plugins) to automatically generate some serialization code.
