### ISSUE TITLE
DatabaseDao - method to clear table

### ISSUE THREAD

**Issue by LukaszGrela** [yahoo/squidb#16]
I wasn't able to find a quick "clear table" method, I've found this to work in that fashion:

        Criterion everywhere = Todo.ID.isNotNull();
        app.todosDao().deleteWhere(Todo.class, everywhere);

is it useful wrapped as a public method of `DatabaseDao` 

    /**
     * Delete all rows in the given {@Link TableModel} table
     * 
     * @param modelClass the model class corresponding to the table to delete from
     * @return the number of rows deleted on success, -1 on failure
     */
    public int deleteAll(Class<? extends TableModel> modelClass){
        return deleteWhere(modelClass, TableModel.ID_PROPERTY.isNotNull());
    }

**Comment by jdkoren** [comment]
You can use `databaseDao.deleteWhere(Model.class, Criterion.all);` to delete all the rows.
