### ISSUE TITLE
Translate this wiki into other languages

### ISSUE THREAD

**Issue by gotokatsuya** [yahoo/squidb#17]
@sbosley 

Sorry for writing on issues. I could not find your email.

Can I translate this wiki into Japanese ?

I think this project is so good.

**Comment by sbosley** [comment]
Thanks for reaching out @gotokatsuya, and thanks for the kind words! Glad to hear you're enjoying the project.

You're more than welcome to translate the wiki into Japanese, but I'm not sure where we'd host it. We might want to set up a separate website where we can host documentation, write blog posts, etc. I'll think about the best way to do that and touch base with some colleagues, and then get back to you.

The only other issue I can think of with maintaining wiki translations is the community would have to be active in updating them whenever we made additions/changes to the library. Perhaps a public wiki on another site would be the best solution...again, I'll think about it and let you know! We'll come up with something though, so if you want to get started, go right ahead, and we'll try to figure out a place to host it soon.

**Comment by gotokatsuya** [comment]
@sbosley Thank you so much ! 

I'm looking forward to hearing from you.

**Comment by jaredsburrows** [comment]
@gotokatsuya Have you got a PR for this?

**Comment by sbosley** [comment]
I never was able figure out a good way of hosting other wiki translations, so I think at this point it would be best that if community members want to maintain another translation, they can post it elsewhere/in a separate github repo, and we can link to it from our main wiki if all looks good. We probably don't have the time/resources to maintain other translations ourselves, but if any user or community member wants to take on the task, I say go for it. Going to close this issue, but anyone let us know if you decide to maintain forks of our documentation!
