### ISSUE TITLE
Code generator should probably warn if you pass it unrecognized options

### ISSUE THREAD

**Issue by jdkoren** [yahoo/squidb#183]
Since the code generator accepts options that modify the behavior of plugins, it would be useful if options that are unrecognized print a warning during builds. This would make it apparent if an option is extraneous, has a typo in it, or similar.

Note that code generator plugins could also accept options that are unknown to squidb; perhaps the plugins themselves can report the options they accept.

**Comment by sbosley** [comment]
Closed by #203, nice work @jdkoren!
