### ISSUE TITLE
Use net.ltgt.apt for core modules when using j2objc

### ISSUE THREAD

**Issue by aminelaadhari** [yahoo/squidb#185]
When using J2objc it doesn't make sense to use com.android.library for core modules. 

There is an equivalent plugin to android-apt which works with java projects: 
https://plugins.gradle.org/plugin/net.ltgt.apt
https://bitbucket.org/hvisser/android-apt/issues/18/support-java-plugin

This plugin should be used when the core module is intended to be translated with j2objc.

**Comment by sbosley** [comment]
Actually, j2objc supports a few Android packages, as seen here: http://j2objc.org/reference/packages.html. We've found that we often want to take advantage of these classes, so we still recommend setting up any shared code as an Android library project. Of course, there are many different ways one could set up a j2objc project; we've just documented the particular things we've found most useful.

**Comment by aminelaadhari** [comment]
It makes sense. Thanks for the explanation.

**Comment by sbosley** [comment]
Sure thing! If you find that a different project setup works better for your use case, feel free to write up some details and we can see about adding it to the wiki.
