### ISSUE TITLE
Serialize any object to JSON

### ISSUE THREAD

**Issue by iambibhas** [yahoo/squidb#189]
With version 3.0, Is there any easy way to serialize an object to JSON without changing their model spec? I don't want to define columns as JSONColumn. Just want to take an object of a model and serialize it to JSON.

**Comment by sbosley** [comment]
So in other words you'd like to flatten a SquiDB model object to a set of key-value pairs as JSON? This isn't a built-in function, but it should be very easy to implement yourself -- you can use `AbstractModel#getMergedValues()` on any model object to get a set of key-value pairs for the current state of that model. This will be represented as a `ValuesStorage` object, on which you can call `valuesSet()` to get a `Set<Map.Entry<String, Object>>`, and then write those key-value pairs to a JSON string using your favorite JSON library.

This also isn't restricted to 3.0 -- `getMergedValues()` exists in 2.0 as well, although it returns a `ContentValues`. The same idea would apply though. Hope that helps!

**Comment by iambibhas** [comment]
@sbosley Thanks! That worked! 

```
public JSONObject modelObjectToJson(TableModel obj) {
    JSONObject jobj = new JSONObject();
    try {
        for (Map.Entry<String, Object> s : obj.getMergedValues().valueSet()) {
            jobj.put(s.getKey(), s.getValue() == null ? "" : s.getValue());
        }
    } catch (JSONException e) {
        Log.d(this.toString(), e.getMessage());
        e.printStackTrace();
    }
    return jobj;
}
```

I was thinking about the next step and taking a cursor and turn that into a `JSONArray`. But having trouble guessing the model type and iterating over the cursor.

**Comment by sbosley** [comment]
👍 glad that worked!

In terms of guessing the model type, I'd suggest passing around the model class that you passed to `SquidDatabase.query()` and using that. You can then get an instance using `modelClass.newInstance()` and use `readPropertiesFromCursor()` to populating it. The cursor iteration itself is just like iterating over a standard android cursor; all the same methods are available.
