### ISSUE TITLE
gson annotations(SerializedName(""), Expose) not retained after the class generation

### ISSUE THREAD

**Issue by preetb123** [yahoo/squidb#194]
annotations not retained in the generated class. If this is by design then how to achieve the gson serialization

**Comment by sbosley** [comment]
This seems to be the same question as issue #189 -- you can refer to the discussion there for ideas.

For the sake of clarity: model specs aren't "real" Java objects, they're just shorthand for generating a table schema. The fields in the spec just generate `Property` declarations; the generated model class doesn't actually have any fields of its own, so there wouldn't be anywhere to copy the annotations to.

Hope that helps! Let us know if you have other questions.
