### ISSUE TITLE
Handling of invalid column names (sql keywords)

### ISSUE THREAD

**Issue by MFlisar** [yahoo/squidb#243]
It would be a nice feature, if the compiler does either of following if column names or similar are named with invalid names in the sense of that those names will result in some sql exception, like for example, a column name like "group".

*Side note/Idea*

I actually thought, that some automatic prefixig could solve that as well. But would not be backwards compatible though...

**Comment by sbosley** [comment]
We've just merged the PR that implements identifier validation. It'll check for SQLite keywords in addition to performing other validation like checking for illegal characters in column or table names. Should be released soon!
