### ISSUE TITLE
How to ignore a property in model

### ISSUE THREAD

**Issue by arashcoder** [yahoo/squidb#246]
Hi. There is a @Ignore annotation, but when i use it, I cannot access that property. So is there a way to tell squidb to ignore a property and not save it as a field in database?
thank you.

**Comment by sbosley** [comment]
Sorry, I'm not sure I fully understand what you're asking. Properties are just a representation of columns in a table, so the idea of a column that isn't saved to the database doesn't really apply. Are you just looking to attach unpersisted metadata to a model object? If so, you can use the "transitory" methods present on all model objects; these methods let you attach arbitrary in-memory objects to any model instance using a key. See [putTransitory()](https://github.com/yahoo/squidb/blob/master/squidb/src/com/yahoo/squidb/data/AbstractModel.java#L459) and [getTransitory()](https://github.com/yahoo/squidb/blob/master/squidb/src/com/yahoo/squidb/data/AbstractModel.java#L473).

Does that answer your question or were you looking for something else?

**Comment by arashcoder** [comment]
Thanks for the reply. I think this is what I'm looking for.
