### ISSUE TITLE
procedure in squidb just like sql 

### ISSUE THREAD

**Issue by ujagarsingh** [yahoo/squidb#281]
I am  using  squidb database in cordova application. that application for android and ios. java code is compile by j2objc for IOS application where i use squidb. now i want to use procedure (like SQL procedure).  
now can i user procedure in squidb and how. please help me it's urgent.

**Comment by sbosley** [comment]
Sorry @ujagarsingh, I'm afraid I don't understand what you're asking. If you're just asking about building SQL queries, you can find documentation on our query builder on this wiki page: https://github.com/yahoo/squidb/wiki/SquiDB's-query-builder. If you're asking something else, please join our chat channel at https://gitter.im/yahoo/squidb and we can try to help you (we use GitHub Issues for bug reports or feature requests, but it's not a great place for extended discussion or support).
