### ISSUE TITLE
Project failed to refresh

### ISSUE THREAD

**Issue by LukaszGrela** [yahoo/squidb#29]
I've refreshed the squidb files with git pull and now in my project I see the error: 

```
    Gradle '...' project refresh failed
    Error:Could not find com.yahoo.squidb:apt-utils:1.0.0.
    Searched in the following locations:
        https://jcenter.bintray.com/com/yahoo/squidb/apt-utils/1.0.0/apt-utils-1.0.0.pom
        https://jcenter.bintray.com/com/yahoo/squidb/apt-utils/1.0.0/apt-utils-1.0.0.jar
        file:/C:/sdk/Android/extras/android/m2repository/com/yahoo/squidb/apt-utils/1.0.0/apt-utils-1.0.0.pom
        file:/C:/sdk/Android/extras/android/m2repository/com/yahoo/squidb/apt-utils/1.0.0/apt-utils-1.0.0.jar
        file:/C:/sdk/Android/extras/google/m2repository/com/yahoo/squidb/apt-utils/1.0.0/apt-utils-1.0.0.pom
        file:/C:/sdk/Android/extras/google/m2repository/com/yahoo/squidb/apt-utils/1.0.0/apt-utils-1.0.0.jar
    Required by:
        TodoOrNotTodo:app:unspecified > com.yahoo.squidb:squidb-processor:1.0.0

Is it me? or something in the library updated that upsets gradle?

**Comment by sbosley** [comment]
Yeah this was my bad. TIL that apparently gradle doesn't seem to use the repositories declared in dependent projects build.gradle. We finally added support for building from prebuilt artifacts, which includes the apt-utils project that the squidb processor depends on, but JCenter mirroring isn't turned on yet.

As a temporary fix, add this to your project's build.gradle:
```
repositories {
    maven { url "https://dl.bintray.com/yahoo/maven" }
}
```

I think as soon as the artifacts are available via JCenter this won't be necessary, so I'll post back when that's set up, hopefully later today.

Sorry for the confusion!

**Comment by LukaszGrela** [comment]
The fix worked.
To others, the temp fix is to be added to `allprojects->repositories`:

    allprojects {
        repositories {
            jcenter()
            //temp fix for Error:Could not find com.yahoo.squidb:apt-utils:1.0.0.
            maven { url "https://dl.bintray.com/yahoo/maven" }
        }
    }

**Comment by sbosley** [comment]
Artifacts are now available via jcenter! Can you try building again without the temp fix? All you should need now is jcenter() in your repositories {} block. If it works for you, feel free to close the issue, and I'll update the wiki to reflect that jcenter is the only repository dependency required.
