### ISSUE TITLE
Models should have a full default constructor (in additon to the default empty one)

### ISSUE THREAD

**Issue by MFlisar** [yahoo/squidb#30]
Think of the person model here: https://github.com/yahoo/squidb/wiki/Defining-table-schemas

You create a person somewhere like following:

    Person p = new Person().setFirstName("firstname").setLastName("lastname").setAge(20);
    dao.persist(p);

Now you add an body size field to it. Problem: how to find all places where you have to update the construction function with the new field? If you would additionally create a constructor like `Person(String firstName, String lastName, int age)` and I want to be save to always initial ALL fields, I just use this one. Because if I change the model, the constructor would change as well (it would become `Person(String firstName, String lastName, int age, int bodySize)`) and therefore I would get compile errors and could directly see them and correct them...

Otherwise, after updating the model, all new persons that I may have forgetten to add an `.setBodySize(...)` would have the default body size... Which I may not want...

**Comment by jdkoren** [comment]
Android Studio has a "find usages" feature that you can use to locate all the places your constructor is called. Methods and constructors with many arguments are generally unwieldy.

**Comment by MFlisar** [comment]
I get your point. I was just used to it as I used greendao in some other projects and liked it like that...

**Comment by sbosley** [comment]
While I agree with @jdkoren and we probably won't be adding an N-arg constructor by default, I've been tossing around some ideas in my head for a big extension of our (currently experimental and rudimentary) [code gen plugin system](https://github.com/yahoo/squidb/wiki/Writing-plugins-for-custom-data-types). I think the ability to add additional methods or constructors to models via a plugin is something that we could do, so once the API is enhanced this kind of thing could be a straightforward plugin to write. I'll post back to this issue when the API is ready!

**Comment by sbosley** [comment]
In the meantime, if you want to enforce that pattern, I'd recommend creating a static helper method, probably in your model spec so it can be copied to the generated model:

```java
public static Person createNewPerson(String firstName, String lastName, int age) {
    return new Person().setFirstName(firstName).setLastName(lastName).setAge(age);
}
```

Then any time you add a new field in your model spec, you just add the same field to this "constructor" method, and be sure to use it anywhere you're creating new objects. Then it should be easy to find things at compile time like you want.

**Comment by sbosley** [comment]
I'm going to close this issue in favor of the plugin API enhancement issue linked above. Thanks for the suggestion!

**Comment by MFlisar** [comment]
Thanks. Using static  helper methods is the thing I'm doing currently...
