### ISSUE TITLE
Support for indizes

### ISSUE THREAD

**Issue by MFlisar** [yahoo/squidb#34]
Do you have that? This would be really nice... In my opinion it should be part of the `@ColumnSpec` but I couldn't find something like that...

**Comment by jdkoren** [comment]
Indeed we do have support for indexes. There's a class called [Index](https://github.com/yahoo/squidb/blob/master/squidb/src/com/yahoo/squidb/sql/Index.java) that you can instantiate directly, or you can create one from a Table object using the static methods [index(String, Property<?>...)](https://github.com/yahoo/squidb/blob/master/squidb/src/com/yahoo/squidb/sql/Table.java#L58) and [uniqueIndex(String name, Property<?>... columns)](https://github.com/yahoo/squidb/blob/master/squidb/src/com/yahoo/squidb/sql/Table.java#L70).

In your subclass of AbstractDatabase, override `getIndexes()` and return the Indexes you want to have created automatically. You will probably have to write an upgrade case in `onUpgrade()`, where you can use [tryCreateIndex(Index)](https://github.com/yahoo/squidb/blob/master/squidb/src/com/yahoo/squidb/data/AbstractDatabase.java#L954).

**Comment by MFlisar** [comment]
Thanks a lot. The `getIndexes` is the one I didn't see

**Comment by sbosley** [comment]
Thanks @jdkoren! Sounds like this question has been answered, so I'm going to close the issue.
