### ISSUE TITLE
Trying to save data

### ISSUE THREAD

**Issue by taimur97** [yahoo/squidb#40]
Hi
Your library is really easily to understand and thanks for this amazing library. I am having an issue 
I am trying to save a string array items using a for loop. What I am doing is creating a new instance of model class each time the loop runs I extract the info from the array put it in the model class instance and call the following method inside the loop

 dao.persist(newPerson);

But I am getting an illegalStateException. I know I am doing something wrong. I searched in the wiki 
and also took a look at the sample but couldn't find a
any help. Can you please tell me how can I save an array of strings? And Can I save two objects(different class and different table) at the same time?

**Comment by jdkoren** [comment]
Can you post a complete stack trace of your exception?

I'm not sure how to answer your question about saving two different models at the same time. You can always create two different objects and call `persist()` on each of them. Is there something else I'm not understanding about what you want to do? Perhaps you can post a code snippet?

**Comment by jdkoren** [comment]
@taimur97 It's been a few weeks since this was opened. Has your issue been resolved?

**Comment by jdkoren** [comment]
This hasn't seen any activity in a while, so I'll assume it's either been resolved or is no longer valid. If that's not the case, please comment here and we can reopen it.
