### ISSUE TITLE
RecyclerView.Adapter implementaion for SquidCursor

### ISSUE THREAD

**Issue by despectra** [yahoo/squidb#41]
Hey!

You've got a very useful class SquidCursorAdapter in your library. It's designed for ListView, however currently Android Framework provides us with more flexible and efficient RecyclerView. Are you planning on implementing RecyclerView.Adapter class specially for SquidCursor?

Thanks in advance!

**Comment by jdkoren** [comment]
We are planning to add one very soon, there are just a few implementation details we're sorting out.

**Comment by sbosley** [comment]
A squidb-recyclerview module was added with SquiDB 2.0 that contains a RecyclerView.Adapter implementation. See [this wiki page](https://github.com/yahoo/squidb/wiki/Using-SquidRecyclerAdapter) for details.
