### ISSUE TITLE
SquidCursorLoader isn't compatible with support-v4 Loaders

### ISSUE THREAD

**Issue by agatti** [yahoo/squidb#44]
Hi there,

  I'm trying to switch some of my manual SquidCursor management code over to SquidCursorLoader, but the application I'm working with needs Fragment and Activity instances to come from support-v4.

  From what I can see, SquidCursorLoader uses android.content.Loader, which makes it incompatible with android.support.v4.app.Fragment and android.support.v4.app.LoaderManager.  Are there any plans to provide something that can work also for support fragments/activities?

Cheers,
Alessandro

**Comment by jdkoren** [comment]
Hi Alessandro,

At one point we did have a support-v4 compatible loader, but we took it out for two reasons: 

1. We didn't want to have the support library as a dependency
2. Android platform distribution numbers show such a small percentage of devices below API 14 that most apps have stopped supporting those levels, which means they have access to the android.content versions of those classes

That being said, there is an easy workaround for you: copy the source of `SquidCursorLoader` into a new class(perhaps with another name to avoid confusion) and change the import statement to 

```java
import android.support.v4.content.AsyncTaskLoader
```

It should just work, but let me know if you run into other problems with that.

**Comment by agatti** [comment]
Hi Jonathan,

  thank you for your prompt response.  Having my own copy of SquidCursorLoader with that simple change in was indeed what I did and it does seem to work here, albeit I'm a bit worried about future maintenance of the application I'm working on when SquiDB gets updated some time in the future.

  Regarding platform distribution, my application has `minsdk` set to 15, but I am still using the Support Library due to nested fragment support being available only from API 17 and higher.  Unfortunately that's the reason for my application (and I guess quite a few others out there) to use `android.support.v4.app.Fragment` and/or `android.support.v4.ActivityCompat` and thus unable to use `SquidCursorLoader` in its current form.

  Maybe you may want to bring the support library dependency back in until API 17 is the widely accepted `minsdk`?

  Still, thanks for your work, using SquiDB has been a terrific experience so far!

**Comment by jdkoren** [comment]
While you do have a valid point, I think it's likely we will keep things the way they are. We don't want to introduce a dependency in apps that don't have/need it, and the workaround is simple enough; in fact, we already mention it [in our wiki pages](https://github.com/yahoo/squidb/wiki/Support-for-Pre-ICS#porting-squidcursorloader).

**Comment by agatti** [comment]
I understand.  Anyway, thank you for the feedback!

I'll document this in my project so whoever will take over on this in the future knows what to do.  Feel free to close the issue and good luck with the project! :)

**Comment by jdkoren** [comment]
Thanks!

**Comment by sbosley** [comment]
@jdkoren what if we brought back the dependency in a separate module/project? squidb-support or something like that. SquiDB itself wouldn't need the dependency, but those who want the support versions of the loaders could still get them. Takes a little extra maintenance effort on our part, but nothing too bad, and we could always deprecate it once API 17 gets more adoption. What do you think?

**Comment by jdkoren** [comment]
That's a viable solution, I just wonder if it's worth the maintenance for just a single class.
