### ISSUE TITLE
[QUERY] Is there a way to have ", " as separator in the groupConcatDistinct

### ISSUE THREAD

**Issue by LukaszGrela** [yahoo/squidb#47]
I'm using suggested methods to concat and group the author list

```

    private static Function<String> authorCase = Function.caseWhen(Author.MIDDLE_NAME.isEmpty(),
            Function.strConcat(Author.NAME, " ", Author.SURNAME),
            Function.strConcat(Author.NAME, " ", Author.MIDDLE_NAME, " ", Author.SURNAME));
    public static  Property.StringProperty AUTHOR = Property.StringProperty.fromFunction(Function.groupConcatDistinct(authorCase), "author");


```

but the results are combines with comma without a space

```
07-17 18:40:35.897  13428-13428/com.greladesign.android.exlibris I/BookShelfAdapter﹕ book=Book
    set values:
    null
    values:
    ean=9788378185512 author=Andrzej Borowiec,Klaudia Stefaniak,Jacek Środa edition=Wydanie I year=2014 title=Chłopak z Warszawy pages=432 isbn=

```

Is there a way to change the separator? e.g. to add the space after comma?

**Comment by jdkoren** [comment]
Unfortunately no. You can only use DISTINCT in an aggregate function if it takes a single argument. Here is the relevant SQLite documentation:

> In any aggregate function that takes a single argument, that argument can be preceded
> by the keyword DISTINCT. In such cases, duplicate elements are filtered before being
> passed into the aggregate function.

**Comment by LukaszGrela** [comment]
@jdkoren I've found this link, could you verify if this can be used in squidb?

http://sqlite.1065341.n5.nabble.com/How-to-use-distinct-in-group-concat-together-with-specified-separator-td21574.html

**Comment by jdkoren** [comment]
That seems like a reasonable workaround if that's the only result column you want, but in your case you want it as one of multiple result columns in a query. The SELECT grammar doesn't allow for `SELECT <anything> FROM <anywhere>` as a result column. Perhaps you can do a join against this query to combine the result with the rest of the columns you are selecting, but I have no idea what the join constraint would be.

In any case it has to be its own query, which you can already build with what SquiDB provides.

**Comment by LukaszGrela** [comment]
:) thanks
