### ISSUE TITLE
Investigate/Add RxJava support

### ISSUE THREAD

**Issue by sbosley** [yahoo/squidb#5]
We have a custom UriNotifier mechanism that allows users of DatabaseDao to automatically notify Uris based on table writes, which means that users can use standard Android ContentObservers to listen for changes. However, it sounds like there's some interest in an RxJava-based approach for listening to DB changes a la SQLBrite.

In looking at SQLBrite's code, their implementation is really similar to how we accumulate a Set<Uri> to notify during transactions, so this is probably pretty doable.

**Comment by iluvmykids130** [comment]
John

**Comment by jenzz** [comment]
Yay, RxJava support would be a great addition! :+1:

**Comment by clertonleal** [comment]
Great!!!

**Comment by plackemacher** [comment]
+1

**Comment by sbosley** [comment]
Just a quick note--I've implemented a version of RxJava support on our 2.0 dev branch, and opened the pull request here: https://github.com/yahoo/squidb/pull/77. If anyone who's interested in this feature wants to give feedback on the proposed API it would be welcome!

**Comment by sbosley** [comment]
The PR has been merged into our dev_2.0 branch; it'll be launched as an addon component when SquiDB 2.0 launches. I'll leave this issue open until then, but feel free to check out the branch and play with it!

**Comment by sbosley** [comment]
SquiDB 2.0 has launched so the squidb-reactive module for basic RxJava support is now available as an optional add-on! See [this wiki page](https://github.com/yahoo/squidb/wiki/Observing-with-RxJava) for details.
