### ISSUE TITLE
Who can provide a complete example of showing how to create a table and showing how to create and operate databases.

### ISSUE THREAD

**Issue by yufengzungzhe** [yahoo/squidb#52]

**Comment by sbosley** [comment]
The [squidb-sample project](https://github.com/yahoo/squidb/tree/master/squidb-sample) is an example of a complete (albeit simple) app that uses squidb to create tables and read/write the sqlite database. I recommend taking a look at the [TasksDatabase](https://github.com/yahoo/squidb/blob/master/squidb-sample/src/main/java/com/yahoo/squidb/sample/database/TasksDatabase.java) class which shows how to create tables in a new database by overriding getTables(), or create tables in a migration with tryCreateTable().

I also recommend you check out the wiki, especially the [Setting up a database](https://github.com/yahoo/squidb/wiki/Setting-up-a-database-for-your-app) and [Using DatabaseDao](https://github.com/yahoo/squidb/wiki/Using-DatabaseDao) pages.

Hope that helps! Feel free to reopen the issue if you have any more specific questions.
