### ISSUE TITLE
how to use Squidb with SQLCipher

### ISSUE THREAD

**Issue by inawlaljar** [yahoo/squidb#63]
I love Squidb ORM. But, I can't seem to be getting it work with SQLCipher. Please help.

**Comment by sbosley** [comment]
Non-standard SQLite builds aren't supported at this time I'm afraid. It is on the roadmap though, being tracked under issue #36, so I'd suggest you follow that issue for updates (I'll close this one as a duplicate). I can't commit to a timeline at this point, but it's definitely something we'd like to do and SQLCipher will be a version we'll include in that effort.
