### ISSUE TITLE
Usability of new @Implement annotation

### ISSUE THREAD

**Issue by dotWee** [yahoo/squidb#66]
Is there any example available for the new @Implement annotation?
I'm searching for a way to implement a custom comparator into model specs.

**Comment by sbosley** [comment]
There's an example in the javadoc for `@Implements`. I've been meaning to add one to the wiki, just haven't gotten around to it yet. For implementing Comparable though:

```java
@TableModelSpec(className = "Person", tableName = "people")
@Implements(interfaceDefinitions = {
    @Implements.InterfaceSpec(interfaceClass=Comparable.class,
        interfaceTypeArgNames="com.mypackage.Person")})
// This should generate class Person implements Comparable<Person>
public class PersonSpec {
    ...

    @ModelMethod // For implementing the interface method
    public static int compareTo(Person instance, Person other) {
        // Implement the comparison here
    }
}
```

Hope that helps!

**Comment by dotWee** [comment]
That helps a lot! Thank you very much!

**Comment by sbosley** [comment]
Sure thing! Maybe I'll just use that example for the wiki, it's a good one :)
