### ISSUE TITLE
Insert or update

### ISSUE THREAD

**Issue by tsuharesu** [yahoo/squidb#84]
I am getting data from an API, and this data already have an id. I set up SquiDB with a Spec, changed to have a @PrimaryKey and everything. The problem is that, when trying to persist the data, Squid thinks my data already exists (because it has an id) and try to UPDATE a row that does not exist :cry: 

```
UPDATE tablename SET something=? WHERE (tablename.id=1)
```

How can I resolve this? 
I could create a @PrimaryKey localId but I don't feel this is correct...

**Comment by sbosley** [comment]
So if I understand correctly, your local row id doubles as a global id?

This will become a bit easier in SquiDB 2.0, when AbstractDatabase and DatabaseDao are unified, but for now, you can subclass DatabaseDao and create a new method that delegates to the protected method `insertRow`:
```java
public class DaoExtension extends DatabaseDao {
    public boolean persistWithId(TableModel item) {
        return insertRow(item, null); // Or specify a conflict algorithm instead of null.
    }
}
```

That being said, unless your API is read-only, I'm not sure using the row id as the guid is the best idea. You might insert a row without an id on a client, at which point SQLite would generate a new row id, which you'd then send to your API--but without any assurance that some other client hadn't done the same thing. If you need to maintain uniqueness based on a non-row id field, it's probably better to create a separate column with a uniqueness constraint and do something like first attempting an update followed by an insert if no rows match (or just an insert on conflict replace if replace semantics work for your use case).

At the moment, squidb only supports primary keys that are synonymous with the row id. We may lift this restriction in the future, but don't have a timeline for that enhancement to share just yet.

Hope that helps!

**Comment by tsuharesu** [comment]
Hmm. Is more or less like this. My app is a client, so I get the objects from the API and just save them locally. All the id logic is on the server, not on the app (no need to be).

Will try to use `updateRow` method.

**Comment by sbosley** [comment]
In that case, I think your best bet is to effectively ignore SquiDB's primary key. All rows would have a row id regardless of whether or not you were using SquiDB, but if the value of the row id isn't important to your app, then you don't need to worry about it. Instead just create a separate column with a uniqueness constraint for the server id without designating that column as a primary key. Then you can either use `persistWithOnConflict(item, ConflictAlgorithm.REPLACE)` or write your own method to try an update before doing an insert.

**Comment by tsuharesu** [comment]
Cool, will try to do that. Thanks!
